### ISSUE TITLE
Bump version/add tag for 0.7

### ISSUE THREAD

**Issue by djc** [rustls/sct.rs#10]
The latest version on crates.io is 0.7, but in the main branch of this repo it still says 0.6.1 (though the latest @ctz commits are from the same date as the release). @ctz do you still have that change in your local working dir, by any chance? If so, want to commit/PR it?

**Comment by ctz** [comment]
Whoops, I released that from an unpushed commit 5b9bbbd31. I've rewritten main to maintain linearity; this has changed d4fca97b3 to be 73b09bed7
