### ISSUE TITLE
Add support to ring 0.17

### ISSUE THREAD

**Issue by donmor** [rustls/sct.rs#16]
ring 0.17 releaseddays ago. Please add 0.17 as oprional dependency aside of 0.16, if it works with it.

**Comment by ctz** [comment]
#15

**Comment by paolobarbolini** [comment]
Can we get this released? I'm currently getting duplicate `ring` versions because of rustls v0.21.8 depending on `sct` v0.7.0

**Comment by ctz** [comment]
Good point! Will prepare 0.7.1 for release shortly.

**Comment by ctz** [comment]
Released! https://crates.io/crates/sct/0.7.1
